/**
 * react-native.config.js — Force-link onnxruntime-react-native
 * ─────────────────────────────────────────────────────────────
 * EAS Build runs `expo prebuild` in the cloud before Gradle compilation.
 * Prebuild invokes the React Native autolinking resolver, which reads this
 * file to inject native packages into the generated MainApplication.kt.
 *
 * Without this file, Expo's managed autolinking may silently skip
 * onnxruntime-react-native because its package.json does not carry the
 * `"reactNativeConfig"` key used by some autolinking versions, causing
 * OnnxruntimeModule to be null at runtime →
 *   TypeError: Cannot read property 'install' of null
 *
 * This override explicitly registers the package's Android source dir
 * and provides the exact Java import + instantiation strings that
 * react-native-gradle-plugin writes into the autogenerated
 * PackageList.java / MainApplication.kt.
 *
 * References:
 *   https://github.com/react-native-community/cli/blob/main/docs/autolinking.md
 *   https://github.com/microsoft/onnxruntime-inference-examples
 */

module.exports = {
  dependencies: {
    'onnxruntime-react-native': {
      root: './node_modules/onnxruntime-react-native',
      platforms: {
        android: {
          sourceDir: './android',
          packageImportPath: 'import ai.onnxruntime.reactnative.OnnxruntimePackage;',
          packageInstance: 'new OnnxruntimePackage()',
        },
      },
    },
  },
};
